name: Update Feeds

on:
  schedule:
    - cron: '0 */48 * * *'  # Ejecutar cada 48 horas
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add feeds/
          git commit -m "Update feeds [skip ci]" || echo "No changes to commit"
          git push 